### ISSUE TITLE
Missing Sentry.framework on iOS

### ISSUE THREAD

**Issue by alexbonhomme** [getsentry/sentry-cordova#2]
Hi!

I can't install the plugin on iOS platform. I got the following message.

```
Cannot find framework "/Users/alex/Development/1_ALEX-ET-MANON/lab/Vliller/vliller/plugins/cordova-plugin-sentry/src/ios/Carthage/Build/iOS/Sentry.framework" for plugin cordova-plugin-sentry in iOS platform
```
  
I tried with the last version `0.1.1` using `ionic cordova plugin add @sentry/cordova --save`

**Comment by HazAT** [comment]
I am on it!

**Comment by HazAT** [comment]
Hey, this should be fixed with `0.1.3` 👍

**Comment by alexbonhomme** [comment]
Hi @HazAT thanks for your update !

Unfortunately, I have a new problem. I got stuck on : 

```
Adding cordova-plugin-sentry to package.json
Saved plugin info for "cordova-plugin-sentry" to config.xml
no URL provided, fallback to https://sentry.io/
Running Sentry Wizard...
version: 0.7.4 | sentry-cli version: 1.27.1
Sentry Wizard will you help to configure your project
Thank you for using Sentry :)
? Select the platforms you like to set up: (Press <space> to select, <a> to togg
le all, <i> to invert selection)
❯◉ iOS
 ◉ Android
```

I can't do anything except `ctrl + C` to kill the process :-(

**Comment by HazAT** [comment]
@alexbonhomme Can you tell me which command you are running?
Does it not accept input, like pressing enter?

Try to prefix your command with `SENTRY_WIZARD_PLATFORM='["ios","android"]'` this should prevent asking for the platform.

**Comment by alexbonhomme** [comment]
I'm using `ionic cordova plugin add @sentry/cordova`

If I prefix the command like you suggested it seems to work better, but then I'm stuck on : 
```
🎉  Successfully set up Sentry for your project 🎉
```

like it's waiting for some thing...

**Comment by alexbonhomme** [comment]
It seems to work better using directly `SENTRY_WIZARD_PLATFORM='["ios","android"]' cordova plugin add @sentry/cordova -S` but I got an error with the iOS platform.

```
Error: Expected "/*", "//", or "{" but "u" found.
```

**Comment by alexbonhomme** [comment]
Ok i fixed the iOS error by rm/add the platform. Seems to be ok with the cordova command without the Ionic wrapper.

**Comment by HazAT** [comment]
I've updated the docs to reflect this behavior, you have to indeed run it without `ionic` otherwise the input will not work.

**Comment by HazAT** [comment]
Sorry and thank you for helping iron out this inital issues! 🍻

**Comment by alexbonhomme** [comment]
Hey @HazAT !

Thanks for your update. Unfortunately it doesn't work :-(

I have the following error on iOS : 

```
Error: Expected "/*", "//", or "{" but "u" found.
```

and the project make xcode crash.

Not better on Android : 

```
Error: sentryCli.createRelease is not a function
```

Some information of my setup

```
cordova (Cordova CLI) : 7.1.0
Android SDK Tools : 26.1.1
ios-deploy        : 1.9.2
ios-sim           : 6.0.0
Node              : v6.10.2
npm               : 3.10.10
OS                : macOS High Sierra
Xcode             : Xcode 9.2 Build version 9C40b
```

**Comment by HazAT** [comment]
@alexbonhomme sorry for all the troubles you run into.
I've just released an update which should fix the issue on Android.
I will check again for iOS.

**Comment by HazAT** [comment]
Hey @alexbonhomme,
I've just tried to setup a clean project with Ionic, here are the steps that I took:
```
ionic start ionic tabs
cd ionic
ionic cordova platform add android
ionic cordova platform add ios
cordova plugin add @sentry/cordova
yarn add @sentry/cordova
ionic cordova build android --prod --release
ionic cordova build ios --prod --release
```

Everything worked fine!
So the Android issue you had should surely be fixed, I don't actually know where the error on iOS is coming from.
`Error: Expected "/*", "//", or "{" but "u" found.`

**Comment by HazAT** [comment]
So if you get this error 
`Error: Expected "/*", "//", or "{" but "u" found.`
You have to remove and add the platform again, this fixes it.
`cordova platform rm ios` `cordova platform add ios`

**Comment by tobiasmuecksch** [comment]
@HazAT I have this issue, but removing and re-adding the iOS platform doesn't fix it for me...
