### ISSUE TITLE
Error when adding plugin to Ionic 1 project

### ISSUE THREAD

**Issue by yosikal** [getsentry/sentry-cordova#20]
Error during processing of action! Attempting to revert...
Failed to install 'sentry-cordova': Error: Uh oh!
ENOENT: no such file or directory, open 'C:\code\mobile-app\vac-mobile-app\main-project\plugins\sentry-cordova\www\SentryCordova.js'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at install (C:\code\mobile-app\vac-mobile-app\main-project\platforms\android\cordova\lib\pluginHandlers.js:173:36)
    at Object.process (C:\code\mobile-app\vac-mobile-app\main-project\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\code\mobile-app\vac-mobile-app\main-project\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (C:\code\mobile-app\vac-mobile-app\main-project\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
    at C:\code\mobile-app\vac-mobile-app\main-project\platforms\android\cordova\Api.js:243:74
    at _fulfilled (C:\code\mobile-app\vac-mobile-app\main-project\platforms\android\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\code\mobile-app\vac-mobile-app\main-project\platforms\android\cordova\node_modules\q\q.js:883:30)
Error: Uh oh!
ENOENT: no such file or directory, open 'C:\code\mobile-app\vac-mobile-app\main-project\plugins\sentry-cordova\www\SentryCordova.js'

**Comment by HazAT** [comment]
Hey, can you try again, I just published the package also on the name `sentry-cordova`.

**Comment by yosikal** [comment]
Hey,

 

I'm not sure what you mean. I trying following this doc https://docs.sentry.io/clients/cordova/#installation but when I ran cordova plugin add @sentry/cordova I get this error:

 

C:\code\mobile-app\vac-mobile-app\main-project>cordova plugin add @sentry/cordova

Error: Failed to fetch plugin file:node_modules/@sentry/cordova via registry.

Probably this is either a connection problem, or plugin spec is incorrect.

Check your connection and plugin name/version/URL.

Error: cmd: Command failed with exit code 1 Error output:

npm ERR! code ENOLOCAL

npm ERR! Could not install from "node_modules\@sentry\cordova" as it does not contain a package.json file.

 

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\yosikal\AppData\Roaming\npm-cache\_logs\2018-02-26T09_37_46_954Z-debug.log

**Comment by HazAT** [comment]
Can you try to call `cordova plugin add sentry-cordova`?

**Comment by yosikal** [comment]
Still no luck. This what the CLI output:

 

C:\code\mobile-app\vac-mobile-app\main-project>cordova plugin add sentry-cordova

Error: Failed to fetch plugin sentry-cordova via registry.

Probably this is either a connection problem, or plugin spec is incorrect.

Check your connection and plugin name/version/URL.

Error: cmd: Command failed with exit code 1 Error output:

npm ERR! code ENOLOCAL

npm ERR! Could not install from "@sentry\cordova" as it does not contain a package.json file.

 

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\yosikal\AppData\Roaming\npm-cache\_logs\2018-02-26T09_52_29_841Z-debug.log

**Comment by HazAT** [comment]
I guess we have to wait until it shows up in the cordova plugin page
https://cordova.apache.org/plugins/?q=sentry

**Comment by yosikal** [comment]
Ok, now I'm able to install the plugin but I get an exception on :

 

var Sentry = cordova.require("cordova-plugin-sentry.SentryCordovaBundle").default;

**Comment by HazAT** [comment]
@yosikal I need a bit more information than that.
Also to be honest I am not really sure if we even support Ionic 1.
I will close this issue for now, please feel free to create a new one with a detailed bug description.

**Comment by RaulTsc** [comment]
@HazAT any updates here? I cannot even do `cordova plugin add sentry-cordova` ...

**Comment by HazAT** [comment]
@RaulTsc Is your internet connection behind a proxy?
This seems very strange, works here without any issue.

**Comment by RaulTsc** [comment]
Nope, no proxy.

**Comment by HazAT** [comment]
Try removing the `cordova platform rm ios` and re adding everything again?
I suppose you are running the latest version of `sentry-cordova`.
I tried it with cordova `7.0.1` and `8.0.0`

**Comment by RaulTsc** [comment]
Ok. Got it working. Thanks @HazAT 

Getting back my trust in sentry :)
